name: women-kaggle
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.8
  - click
  - networkx
  - pandas
  - seaborn
  - matplotlib
  - scikit-learn
  - flake8
  - coverage
  - python-dotenv
